Education/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Education.Service;
using Education.Dtos;
using Education.DataAccess;

namespace Education.Controllers
{
    public class DashboardController : Controller
    {
        //
        // GET: /Dashboard/
        [HttpGet]
        public ActionResult Dashboard()
        {
            List<DashboardDto> resultCnt = new List<DashboardDto>();
            try
            {
                var DashboardSrv = new DashboardService();
                var userID = Session["LogedUserID"];
                int id = Convert.ToInt16(userID);
                //List<string> result = DashboardSrv.getu(id);
                resultCnt = DashboardSrv.GetListByTempCntId(id);
                //ViewData["Result"] = result;
            }
            catch (Exception ex)
            {
                //Code for exception handling
            }
            return View(resultCnt);
        }


        [HttpGet]
        public ActionResult DashboardNavigation(int item, string type, string Title)
        {
            var repo = new EfUnitOfWork();
            var service = new UserService();
            // var userID = Session["LogedUserID"];
            List<DashboardDto> resultCnt = null;
            try
            {
                var data = repo.SubjectRepository.FindMany(s => s.SemesterId == item).ToList();


                if (type == "sem")
                {
                    resultCnt = service.GetSubject1(item);
                    ViewBag.Type = "sem";
                    ViewBag.semTitle = Title;
                }
                else if (type == "chapter")
                {
                    resultCnt = service.GetChapter1(item);
                    ViewBag.Type = "chapter";
                    ViewBag.subTitle = Title;
                }
                else if (type == "lecture")
                {
                    resultCnt = service.GetLecture1(item);
                    ViewBag.Type = "lecture";
                    ViewBag.lectTitle = Title;
                }
            }
            catch (Exception ex)
            {
                //Code for exception handling
            }
           

            return View(resultCnt);
        }

         [HttpGet]
        public ActionResult test(string item)
        {
            ViewBag.URL = item;
            return View();

        }
	}
}

Education/Controllers/VideoController.cs
using Education.CustomResult;
using Education.Dtos;
using Education.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Education.Controllers
{
    public class VideoController : Controller
    {
        //
        // GET: /Video/
        
        public ActionResult Index(string item, int Id)
        {
            var service = new VideoService();
            LectureDto lectDto = new LectureDto();
            lectDto  = service.GetLectureDetails(Id);           
            ViewBag.URL = item;            
            return View(lectDto);
        }

        public ActionResult Lecture()
        {
            var service = new VideoService();
            List<LectureDto> lectDto = new List<LectureDto>();
            lectDto = service.GetAllLecture();
           
            return View(lectDto);
        }
	}
}

Education/Views/Dashboard/Dashboard.cshtml
@model List<Education.Dtos.DashboardDto>
@{
    ViewBag.Title = "Dashboard";
}
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<html>
<head>
    <title>Dashboard</title>
</head>


<body>

    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row">
                
            </div>
            <div class="table-responsive">
                <table class="table table-bordered table-hover table-striped" align="center">


                    @foreach (var m in Model)
                    {
                        if (m.SDto.Count == 0 && m.subDto.Count == 0 && m.chapDto.Count == 0)
                        {
                            <tr>
                                <td colspan="5"><h4>You have not subscribed to this portal.</h4></td>
                            </tr>
                        }
                        else
                        {
                            <div class="col-lg-12">
                                <h2 class="page-header">Your Subscription details</h2><br />
                            </div>
                            <tr style="background-color: #AEAEAE; ">
                                <th>Subscription Type</th>
                                <th>Details</th>
                                <th>Start Date</th>
                                <th>End Date</th>
                                <th>Remaining Days</th>
                            </tr>
                            foreach (var sem in m.SDto)
                            {

                                <tr>

                                    <td><label id="lblSemester" title="Semester" style="color: #4B4B4B; font-weight: lighter">Semester</label></td>
                                    <td>@Html.ActionLink(sem.SemesterTitle, "DashboardNavigation", "Dashboard", new { item = sem.Id, type = "sem", Title = sem.SemesterTitle }, new { style = "color: #4B4B4B;  font-weight:lighter" })</td>
                                    <td>@Html.Label(sem.CreatedDate.ToString(), new { style = "color: #4B4B4B;  font-weight:lighter" })</td>
                                    <td>@Html.Label(sem.EndDate.ToString(), new { style = "color: #4B4B4B;  font-weight:lighter" })</td>
                                    <td>@Html.Label(sem.DateDiff, new { style = "color: #4B4B4B;  font-weight:lighter" })</td>
                                </tr>
                            }
                            foreach (var Sub in m.subDto)
                            {

                                <tr>
                                    <td><label id="lblSubject" title="Subject" style="color: #4B4B4B; font-weight: lighter">Subject</label></td>
                                    <td>@Html.ActionLink(Sub.SubjectTitle, "DashboardNavigation", "Dashboard", new { item = Sub.Id, type = "chapter", Title = Sub.SubjectTitle }, new { style = "color: #4B4B4B;  font-weight:lighter" })</td>
                                    <td>@Html.Label(Sub.CreatedDate.ToString(), new { style = "color: #4B4B4B;  font-weight:lighter" })</td>
                                    <td>@Html.Label(Sub.EndDate.ToString(), new { style = "color: #4B4B4B;  font-weight:lighter" })</td>
                                    <td>@Html.Label(Sub.DateDiff, new { style = "color: #4B4B4B;  font-weight:lighter" })</td>
                                </tr>

                            }
                            foreach (var Chap in m.chapDto)
                            {


                                <tr>
                                    <td><label id="lblChapter" title="Chapter" style="color: #4B4B4B; font-weight: lighter">Chapter</label></td>
                                    <td>@Html.ActionLink(Chap.Title, "DashboardNavigation", "Dashboard", new { item = Chap.Id, type = "lecture", Title = Chap.Title }, new { style = "color: #4B4B4B;  font-weight:lighter" })</td>
                                    <td>@Html.Label(Chap.CreatedDate.ToString(), new { style = "color: #4B4B4B;  font-weight:lighter" })</td>
                                    <td>@Html.Label(Chap.EndDate.ToString(), new { style = "color: #4B4B4B;  font-weight:lighter" })</td>
                                    <td>@Html.Label(Chap.DateDiff, new { style = "color: #4B4B4B;  font-weight:lighter" })</td>

                                </tr>
                            }
                        }
                    }

                    <tr>
                        @*<td colspan="3"><input type="submit" value="Pay By Net Banking" class="btn btn-default" /></td>*@
                    </tr>
                </table>
            </div>
        </div>
    </div>


</body>
</html>

Education/Views/Dashboard/DashboardNavigation.cshtml
@model List<Education.Dtos.DashboardDto>
@{
    ViewBag.Title = "Dashboard Navigation";
}

<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header" align="center">Details</h2><br />
            </div>
        </div>
        @if (ViewBag.Type == "sem")
        {
            <div>
                <a href="#SemI" class="list-group-item test" data-toggle="collapse" data-parent="#SemI" data-target="#demo1">@ViewBag.semTitle</a>

                <div class="nav-collapse collapse list-group-submenu" id="demo1">
                    @foreach (var m in Model)
                    {
                        if (m.subDto.Count != 0)
                        {
                            foreach (var sub in m.subDto)
                            {
                                var subid = "#demo" + sub.Id;
                                var nsubid = "demo" + sub.Id;
                                <a href="#Sub1" class="list-group-item test" data-parent="#Sub1" data-toggle="collapse" data-target="@subid">@Html.Label(sub.SubjectTitle, new { style = "color: #000000;  font-weight:lighter" })</a>

                                <div class="nav-collapse collapse list-group-submenu list-group-submenu-1" id="@nsubid">
                                    @foreach (var c in m.chapDto)
                                    {

                                        if (sub.Id == c.SubjectId)
                                        {
                                            if (m.chapDto.Count != 0 || m.chapDto.Count != null)
                                            {

                                                <a href="#chap" class="list-group-item test" data-parent="#chap" data-toggle="collapse">@Html.Label(c.Title, new { style = "color: #000000;  font-weight:lighter" })</a>

                                                <div class="collapse list-group-submenu list-group-submenu-1" id="chap">
                                                    @foreach (var lect in m.lectDto)
                                                    {

                                                        if (c.Id == lect.ChapterId)
                                                        {
                                                            if (m.lectDto.Count != 0 || m.lectDto.Count != null)
                                                            {

                                                                int id = lect.Id;                                                                
                                                                @Html.ActionLink(lect.LectureTitle, "Index", "Video", new { item = lect.VideoURL, Id=lect.Id})                                                                

                                                            }
                                                        }
                                                    }
                                                </div>


                                            }
                                        }
                                    }
                                </div>
                            }

                        }
                    }
                </div>
            </div>
        }

        @if (ViewBag.Type == "chapter")
        {
            <div>
                <a href="#SemI" class="list-group-item test" data-toggle="collapse" data-parent="#SemI" data-target="#demo1">@ViewBag.subTitle</a>

                <div class="nav-collapse collapse list-group-submenu" id="demo1">
                    @foreach (var m in Model)
                    {
                        if (m.chapDto.Count != 0 || m.chapDto.Count != null)
                        {

                            foreach (var Chap in m.chapDto)
                            {
                                <a href="#demo2" class="list-group-item test" data-parent="#demo2" data-toggle="collapse" data-target="#demo2">@Html.Label(Chap.Title, new { style = "color: #000000;  font-weight:lighter" })</a>

                                <div class="collapse list-group-submenu list-group-submenu-1" id="demo2">
                                    @foreach (var lect in m.lectDto)
                                        {

                                            if (lect.ChapterId == Chap.Id)
                                            {
                                                if (m.lectDto.Count != 0 || m.lectDto.Count != null)
                                                {
                                                 
                                                    int id = lect.Id;    
                                                     <a href="/Video/Index?item=@lect.VideoURL&Id=@lect.Id" class="list-group-item test" data-parent="#chap">@Html.DisplayFor(p => lect.LectureTitle)</a>                                                 
                                                     @*@Html.ActionLink(lect.LectureTitle, "Index", "Video", new { item = lect.VideoURL, Id = lect.Id }, new { @class="list-group-item test", @data-parent="#chap"})*@                                                     
                                                }
                                            }
                                        }
                                </div>
                            }
                        }

                    }
                </div>

            </div>
        }

        @if (ViewBag.Type == "lecture")
        {
            <div>
                <a href="#SemI" class="list-group-item test" data-toggle="collapse" data-parent="#SemI" data-target="#demo1">@ViewBag.lectTitle</a>

                <div class="nav-collapse collapse list-group-submenu" id="demo1">
                    @foreach (var m in Model)
                    {
                        if (m.lectDto.Count != 0 || m.lectDto.Count != null)
                        {

                            foreach (var Lect in m.lectDto)
                            {
                                                              
                                int id = Lect.Id;                                
                               @*@Html.ActionLink(Lect.LectureTitle, "Index", "Video", new { item = Lect.VideoURL, Id = Lect.Id }, new { style = "color: #4B4B4B;  font-weight:lighter" })*@
                         <a href="/Video/Index?item=@Lect.VideoURL&Id=@Lect.Id" class="list-group-item test" data-parent="#chap">@Html.DisplayFor(p => Lect.LectureTitle)</a>

                            }
                        }

                    }
                </div>

            </div>
        }
        <br />
    </div>
</div>