Education/Controllers/PaymentScreenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Education.Service;
using Education.Dtos;

namespace Education.Controllers

{
    public class PaymentScreenController : Controller
    {
        //
        // GET: /PaymentScreen/
        [HttpGet]
        public ActionResult PaymentScreen(string TotalPrice)
        {
            try
            {
                var PayService = new PaymentService();
                var userID = Session["LogedUserID"];
                int id = Convert.ToInt16(userID);

                List<string> result = PayService.getu(id);
                List<DashboardDto> resultCnt = PayService.GetListByTempCntId(id);
                ViewData["Result"] = result;
                ViewBag.TotalPrice = TotalPrice;
            }
            catch (Exception ex)
            {
                //Code for exception handling
            }
          
            return View();
        }

        [HttpPost]
        public ActionResult PaymentScreenRedirect(string totalamount)
        {
            try
            {
                var PayService = new PaymentService();
                HttpCookie UserSessionid = Request.Cookies["UserCookieId"];
                var userID = Session["LogedUserID"];
                int id = Convert.ToInt16(userID);
                PayService.InsertDataIntoFinalTbl(id, UserSessionid.Value, Convert.ToInt32(totalamount));
            }
            catch (Exception ex)
            {
                //Code for exception handling
            }
           

            return RedirectToAction("Dashboard", "Dashboard");

        }

	}
}

Education/Views/PaymentScreen/PaymentScreen.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var sessionVar = Session["LogedUserID"];
}

<!DOCTYPE html>

<div id="page-wrapper">
    <div class="container-fluid">
        @using (Html.BeginForm("PaymentScreenRedirect", "PaymentScreen", new { totalamount = ViewBag.TotalPrice }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            @Html.AntiForgeryToken()
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="page-header">Payment Information<small> (Please enter your card details to authorise this transaction.)</small></h2>
                </div>
            </div>

            @Html.ValidationSummary()



            <div class="form-group">

                @Html.Label("Debit Card Number", new { @class = "col-md-2 control-label" }) @Html.Label("*", new { @Class = "lablecolor" })
                <div class="col-md-2">
                    @Html.TextBox("TxtBOINo", "", new { @class = "form-control", placeholder = "Debit card number" })

                </div>
            </div>


            <div class="form-group">

                @Html.Label("Name on the Card", new { @class = "col-md-2 control-label" })@Html.Label("*", new { @Class = "lablecolor" })

                <div class="col-md-2">
                    @Html.TextBox("TxtName", "", new { @class = "form-control", placeholder = "Name" })
                </div>
            </div>
            <div class="form-group">

                @Html.Label("Expiry Date", new { @class = "col-md-2 control-label" })@Html.Label("*", new { @Class = "lablecolor" })

                <div class="col-sm-1">

                    @Html.DropDownList("ExpiryMonth", Enumerable.Range(01, 12).Select(x => new SelectListItem { Text = x.ToString() }), "MM", new { @class = "form-control" })
                </div>
                <div class="col-sm-1">
                    @Html.DropDownList("ExpiryYear", Enumerable.Range(2000, 30).Select(x => new SelectListItem { Text = x.ToString() }), "YYYY", new { @class = "form-control" })


                </div>
            </div>
            <div class="form-group">

                @Html.Label("PIN Number", new { @class = "col-md-2 control-label" }) @Html.Label("*", new { @Class = "lablecolor" })

                <div class="col-md-2">
                    @Html.TextBox("TxtPin", "", new { @class = "form-control", placeholder = "Pin Number" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">

                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" class="btn btn-primary" value="Make Payment" />  &nbsp;&nbsp;<input type="submit" class="btn btn-primary" value="Cancel" />
                </div>
            </div>

        }
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}